version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: incode-in-home
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 3308:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
    ports:
      - 8080:8080
